#include <stdio.h>

int main (){
    char a = 'a';
    short b = -22222;
    int c = -9999999;
    long d = -10E11L;
    long long e = -15646516512;
    unsigned char f = 'a';
    unsigned short g = 22222;
    unsigned int h = 9999999;
    unsigned long i = 10E11L;
    unsigned long long j = 15646516512;
    float k = 3.14f;
    double l = 3.1415;
    long double m = 3.14159l;

    printf("%c\n", a);
    printf("%hi\n", a);
    printf("%i\n", a);
    printf("%li\n", a);
    printf("%li\n", a);
    printf("%c\n", a);
    printf("%hu\n", a);
    printf("%u\n", a);
    printf("%lu\n", a);
    printf("%lu\n", a);
    printf("%f\n", a);
    printf("%lf\n", a);
    printf("%Lf\n\n", a);

    printf("%c\n", b);
    printf("%hi\n", b);
    printf("%i\n", b);
    printf("%li\n", b);
    printf("%li\n", b);
    printf("%c\n", b);
    printf("%hu\n", b);
    printf("%u\n", b);
    printf("%lu\n", b);
    printf("%lu\n", b);
    printf("%f\n", b);
    printf("%lf\n", b);
    printf("%Lf\n\n", b);

    printf("%c\n", c);
    printf("%hi\n", c);
    printf("%i\n", c);
    printf("%li\n", c);
    printf("%li\n", c);
    printf("%c\n", c);
    printf("%hu\n", c);
    printf("%u\n", c);
    printf("%lu\n", c);
    printf("%lu\n", c);
    printf("%f\n", c);
    printf("%lf\n", c);
    printf("%Lf\n\n", c);

    printf("%c\n", d);
    printf("%hi\n", d);
    printf("%i\n", d);
    printf("%li\n", d);
    printf("%li\n", d);
    printf("%c\n", d);
    printf("%hu\n", d);
    printf("%u\n", d);
    printf("%lu\n", d);
    printf("%lu\n", d);
    printf("%f\n", d);
    printf("%lf\n", d);
    printf("%Lf\n\n", d);

    printf("%c\n", e);
    printf("%hi\n", e);
    printf("%i\n", e);
    printf("%li\n", e);
    printf("%li\n", e);
    printf("%c\n", e);
    printf("%hu\n", e);
    printf("%u\n", e);
    printf("%lu\n", e);
    printf("%lu\n", e);
    printf("%f\n", e);
    printf("%lf\n", e);
    printf("%Lf\n\n", e);

    printf("%c\n", f);
    printf("%hi\n", f);
    printf("%i\n", f);
    printf("%li\n", f);
    printf("%li\n", f);
    printf("%c\n", f);
    printf("%hu\n", f);
    printf("%u\n", f);
    printf("%lu\n", f);
    printf("%lu\n", f);
    printf("%f\n", f);
    printf("%lf\n", f);
    printf("%Lf\n\n", f);

    printf("%c\n", g);
    printf("%hi\n", g);
    printf("%i\n", g);
    printf("%li\n", g);
    printf("%li\n", g);
    printf("%c\n", g);
    printf("%hu\n", g);
    printf("%u\n", g);
    printf("%lu\n", g);
    printf("%lu\n", g);
    printf("%f\n", g);
    printf("%lf\n", g);
    printf("%Lf\n\n", g);

    printf("%c\n", h);
    printf("%hi\n", h);
    printf("%i\n", h);
    printf("%li\n", h);
    printf("%li\n", h);
    printf("%c\n", h);
    printf("%hu\n", h);
    printf("%u\n", h);
    printf("%lu\n", h);
    printf("%lu\n", h);
    printf("%f\n", h);
    printf("%lf\n", h);
    printf("%Lf\n\n", h);

    printf("%c\n", i);
    printf("%hi\n", i);
    printf("%i\n", i);
    printf("%li\n", i);
    printf("%li\n", i);
    printf("%c\n", i);
    printf("%hu\n", i);
    printf("%u\n", i);
    printf("%lu\n", i);
    printf("%lu\n", i);
    printf("%f\n", i);
    printf("%lf\n", i);
    printf("%Lf\n\n", i);

    printf("%c\n", j);
    printf("%hi\n", j);
    printf("%i\n", j);
    printf("%li\n", j);
    printf("%li\n", j);
    printf("%c\n", j);
    printf("%hu\n", j);
    printf("%u\n", j);
    printf("%lu\n", j);
    printf("%lu\n", j);
    printf("%f\n", j);
    printf("%lf\n", j);
    printf("%Lf\n\n", j);

    printf("%c\n", k);
    printf("%hi\n", k);
    printf("%i\n", k);
    printf("%li\n", k);
    printf("%li\n", k);
    printf("%c\n", k);
    printf("%hu\n", k);
    printf("%u\n", k);
    printf("%lu\n", k);
    printf("%lu\n", k);
    printf("%f\n", k);
    printf("%lf\n", k);
    printf("%Lf\n\n", k);

    printf("%c\n", l);
    printf("%hi\n", l);
    printf("%i\n", l);
    printf("%li\n", l);
    printf("%li\n", l);
    printf("%c\n", l);
    printf("%hu\n", l);
    printf("%u\n", l);
    printf("%lu\n", l);
    printf("%lu\n", l);
    printf("%f\n", l);
    printf("%lf\n", l);
    printf("%Lf\n\n", l);

    printf("%c\n", m);
    printf("%hi\n", m);
    printf("%i\n", m);
    printf("%li\n", m);
    printf("%li\n", m);
    printf("%c\n", m);
    printf("%hu\n", m);
    printf("%u\n", m);
    printf("%lu\n", m);
    printf("%lu\n", m);
    printf("%f\n", m);
    printf("%lf\n", m);
    printf("%Lf\n\n", m);

    return 0;
}